### ISSUE TITLE
Core Rust Library Support

### ISSUE THREAD

**Issue by stevenhartley** [eclipse-uprotocol/uprotocol-rust#10]
uProtocol core library written in Rust

**Comment by PLeVasseur** [comment]
Hi @stevenhartley, had a question for you --

Does this entail implementation of the APIs for all the [protobuf specs in here](https://github.com/eclipse-uprotocol/uprotocol-core-api/tree/main/src/main/proto) according to the [uprotocol-spec repo](https://github.com/eclipse-uprotocol/uprotocol-spec)? Or some subset?

Perhaps we could break this issue up into the pieces to implement and prioritize them so folks know where to pick up work at and allow us to close out finished work.

What do you think?

Cheers,
Pete

**Comment by stevenhartley** [comment]
This is to implement https://github.com/eclipse-uprotocol/uprotocol-spec/blob/main/languages.adoc so the language SDK, not the platform.

**Comment by PLeVasseur** [comment]
Gotcha! Thanks for the pointer.

**Comment by sophokles73** [comment]
@stevenhartley is there any criteria for when this issue could/should be closed? Given that the initial code has been merged, I would propose to close this issue and improve the code based on additional issues/PRs.

BTW the definitions made in https://github.com/eclipse-uprotocol/uprotocol-spec/blob/main/languages.adoc seem to be quite strict, e.g. when it comes to source code layout and distribution of functionality. Apart from trying to provide a comparable UX between the different SDKs, is there any particular reason for maintaining these requirements? In the Rust SDK we have already broken some of the requirements by eliminating the `serializer` module for UUIDs and I intend to remove the corresponding `validator` module as well (#13) ...

WDYT?

**Comment by stevenhartley** [comment]
Yes we can close and add issues for follow on work. 

For the language spec, the goal mainly was for functionality (to make sure the functionality is there and less on the UX) but I see what you mean for how it reads. I'm OK to loosen the requirements if they are hindering you from optimizing the implementation in Rust.
