### ISSUE TITLE
Listener type definition

### ISSUE THREAD

**Issue by Mallets** [eclipse-uprotocol/uprotocol-rust#14]
Current [listener type](https://github.com/eclipse-uprotocol/uprotocol-rust/blob/dcc61ef5198f7db0776983b371a30c0f8ddc9bbd/src/transport/datamodel/utransport.rs#L62) is defined as follows:
```rust
listener: Box<dyn Fn(UMessage) + Send + 'static>
```

From the current definition, I foresee two main issues:

1. The callback only accepts a `UMessage`. It is therefore impossible for the `uTransport` concrete implementation to notify the upper logic about errors.
2. The callback has the following trait bounds: `Send + 'static`. However, being `Sync` not required, it may be an issue in multi-threaded scenarios. E.g. on [zenoh](https://docs.rs/zenoh/0.10.0-rc/zenoh/subscriber/struct.SubscriberBuilder.html#method.callback) the subscriber callback is expected to be `Sync` because the `async` executor is multi-threaded and the callback could be called from different threads every time.

What I'd like then to discuss in this issue is the possibility to modify the listener type to the following: 
```rust
listener: Box<dyn Fn(Result<UMessage, UStatus>) + Send + Sync + 'static>
```

I'm open to discussion.

**Comment by sophokles73** [comment]
FMPOV using `Fn(Result<UMessage, UStatus>)` shouldn't be a problem at all.

Regarding the adding of the `Sync` Trait bound:

In general this seems to make a lot of sense. However, I will need to make some practical experiments before issuing an educated opinion :-)
